// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mv_mult
NumericVector mv_mult(NumericMatrix X, NumericVector beta);
RcppExport SEXP _bicre_mv_mult(SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(mv_mult(X, beta));
    return rcpp_result_gen;
END_RCPP
}
// expect_cum_weibull_cpp
NumericVector expect_cum_weibull_cpp(Nullable<NumericVector> t_, double k, double b);
RcppExport SEXP _bicre_expect_cum_weibull_cpp(SEXP t_SEXP, SEXP kSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type t_(t_SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(expect_cum_weibull_cpp(t_, k, b));
    return rcpp_result_gen;
END_RCPP
}
// expect_cum_weibull_inverse_cpp
NumericVector expect_cum_weibull_inverse_cpp(Nullable<NumericVector> m_, double k, double b);
RcppExport SEXP _bicre_expect_cum_weibull_inverse_cpp(SEXP m_SEXP, SEXP kSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type m_(m_SEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(expect_cum_weibull_inverse_cpp(m_, k, b));
    return rcpp_result_gen;
END_RCPP
}
// expect_cum_weibull_tvc_cpp
NumericVector expect_cum_weibull_tvc_cpp(Nullable<NumericVector> t_, NumericVector lin_pred, NumericVector t_breaks, double k, double b);
RcppExport SEXP _bicre_expect_cum_weibull_tvc_cpp(SEXP t_SEXP, SEXP lin_predSEXP, SEXP t_breaksSEXP, SEXP kSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type t_(t_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lin_pred(lin_predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t_breaks(t_breaksSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(expect_cum_weibull_tvc_cpp(t_, lin_pred, t_breaks, k, b));
    return rcpp_result_gen;
END_RCPP
}
// expect_cum_weibull_tvc_inverse_cpp
NumericVector expect_cum_weibull_tvc_inverse_cpp(Nullable<NumericVector> m_, NumericVector lin_pred, NumericVector t_breaks, double k, double b);
RcppExport SEXP _bicre_expect_cum_weibull_tvc_inverse_cpp(SEXP m_SEXP, SEXP lin_predSEXP, SEXP t_breaksSEXP, SEXP kSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type m_(m_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lin_pred(lin_predSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t_breaks(t_breaksSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(expect_cum_weibull_tvc_inverse_cpp(m_, lin_pred, t_breaks, k, b));
    return rcpp_result_gen;
END_RCPP
}
// generate_events_poisson1
std::vector<double> generate_events_poisson1(double t_start, double t_end);
RcppExport SEXP _bicre_generate_events_poisson1(SEXP t_startSEXP, SEXP t_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_start(t_startSEXP);
    Rcpp::traits::input_parameter< double >::type t_end(t_endSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_events_poisson1(t_start, t_end));
    return rcpp_result_gen;
END_RCPP
}
// generate_events_no0_poisson1
std::vector<double> generate_events_no0_poisson1(double t_start, double t_end);
RcppExport SEXP _bicre_generate_events_no0_poisson1(SEXP t_startSEXP, SEXP t_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t_start(t_startSEXP);
    Rcpp::traits::input_parameter< double >::type t_end(t_endSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_events_no0_poisson1(t_start, t_end));
    return rcpp_result_gen;
END_RCPP
}
// ltrgamma
std::vector<double> ltrgamma(int n, NumericVector shapes, NumericVector scales, double truncate);
RcppExport SEXP _bicre_ltrgamma(SEXP nSEXP, SEXP shapesSEXP, SEXP scalesSEXP, SEXP truncateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type shapes(shapesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scales(scalesSEXP);
    Rcpp::traits::input_parameter< double >::type truncate(truncateSEXP);
    rcpp_result_gen = Rcpp::wrap(ltrgamma(n, shapes, scales, truncate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bicre_mv_mult", (DL_FUNC) &_bicre_mv_mult, 2},
    {"_bicre_expect_cum_weibull_cpp", (DL_FUNC) &_bicre_expect_cum_weibull_cpp, 3},
    {"_bicre_expect_cum_weibull_inverse_cpp", (DL_FUNC) &_bicre_expect_cum_weibull_inverse_cpp, 3},
    {"_bicre_expect_cum_weibull_tvc_cpp", (DL_FUNC) &_bicre_expect_cum_weibull_tvc_cpp, 5},
    {"_bicre_expect_cum_weibull_tvc_inverse_cpp", (DL_FUNC) &_bicre_expect_cum_weibull_tvc_inverse_cpp, 5},
    {"_bicre_generate_events_poisson1", (DL_FUNC) &_bicre_generate_events_poisson1, 2},
    {"_bicre_generate_events_no0_poisson1", (DL_FUNC) &_bicre_generate_events_no0_poisson1, 2},
    {"_bicre_ltrgamma", (DL_FUNC) &_bicre_ltrgamma, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bicre(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
