# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_mult <- function(X, beta) {
    .Call(`_bicre_mv_mult`, X, beta)
}

expect_cum_weibull_cpp <- function(t_, k = 1, b = 1) {
    .Call(`_bicre_expect_cum_weibull_cpp`, t_, k, b)
}

expect_cum_weibull_inverse_cpp <- function(m_, k = 1, b = 1) {
    .Call(`_bicre_expect_cum_weibull_inverse_cpp`, m_, k, b)
}

expect_cum_weibull_tvc_cpp <- function(t_, lin_pred = 0L, t_breaks = as.numeric( c()), k = 1, b = 1) {
    .Call(`_bicre_expect_cum_weibull_tvc_cpp`, t_, lin_pred, t_breaks, k, b)
}

expect_cum_weibull_tvc_inverse_cpp <- function(m_, lin_pred = 0L, t_breaks = as.numeric( c()), k = 1, b = 1) {
    .Call(`_bicre_expect_cum_weibull_tvc_inverse_cpp`, m_, lin_pred, t_breaks, k, b)
}

generate_events_poisson1 <- function(t_start, t_end) {
    .Call(`_bicre_generate_events_poisson1`, t_start, t_end)
}

generate_events_no0_poisson1 <- function(t_start, t_end) {
    .Call(`_bicre_generate_events_no0_poisson1`, t_start, t_end)
}

ltrgamma <- function(n, shapes, scales, truncate) {
    .Call(`_bicre_ltrgamma`, n, shapes, scales, truncate)
}

